process.env.NODE_ENV = 'test';
process.env.DATABASE_URL =
  process.env.TEST_DATABASE_URL ??
  'postgresql://bn:bn_dev_password@localhost:5433/bory_norbert_test?schema=public';
process.env.REDIS_URL = process.env.TEST_REDIS_URL ?? 'redis://localhost:6380';
process.env.JWT_ACCESS_SECRET = 'test-access-secret-abcdefghijklmnop';
process.env.JWT_REFRESH_SECRET = 'test-refresh-secret-abcdefghijklmnop';
process.env.QR_SIGNING_SECRET = 'test-qr-secret-abcdefghijklmnop';
process.env.MOCK_PROVIDERS_ENABLED = 'true';
process.env.ORANGE_MODE = 'mock';
process.env.OTP_MODE = 'mock';
process.env.BLOCKCHAIN_PROVIDER = 'mock';
process.env.REAL_MONEY_MODE = 'false';
process.env.REAL_CRYPTO_MODE = 'false';
process.env.PAYMENT_WINDOW_SECONDS = '900';
process.env.QUOTE_SWEEP_INTERVAL_SECONDS = '3600';
process.env.CRYPTO_REQUIRED_CONFIRMATIONS = '3';
process.env.CORS_ORIGIN = 'http://localhost:3000';
process.env.DISABLE_SCHEDULERS = 'true';
