import { CryptoOrderStatus } from '@prisma/client';
import { TransitionTable } from '../../common/state-machine/state-machine';

type S = CryptoOrderStatus;

const TERMINAL: S[] = ['COMPLETED', 'FAILED', 'EXPIRED', 'CANCELLED', 'REFUNDED'];

export const BUY_TRANSITIONS = new TransitionTable<S>(
  'CryptoOrder(BUY)',
  {
    CREATED: ['QUOTE_LOCKED', 'CANCELLED', 'EXPIRED'],
    QUOTE_LOCKED: ['USDT_RESERVED', 'CANCELLED', 'EXPIRED'],
    USDT_RESERVED: ['AWAITING_PAYMENT', 'CANCELLED', 'EXPIRED'],
    AWAITING_PAYMENT: ['PAYMENT_DETECTED', 'CANCELLED', 'EXPIRED', 'FAILED', 'UNDER_REVIEW'],
    PAYMENT_DETECTED: ['PAYMENT_RECONCILING', 'FAILED', 'UNDER_REVIEW'],
    PAYMENT_RECONCILING: ['PAYMENT_VERIFIED', 'UNDER_REVIEW', 'FAILED'],
    PAYMENT_VERIFIED: ['USDT_PROCESSING', 'UNDER_REVIEW'],
    USDT_PROCESSING: ['USDT_SENT', 'FAILED', 'UNDER_REVIEW'],
    USDT_SENT: ['COMPLETED', 'UNDER_REVIEW'],
    UNDER_REVIEW: ['USDT_PROCESSING', 'PAYMENT_VERIFIED', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED'],
    COMPLETED: [],
    FAILED: [],
    EXPIRED: [],
    CANCELLED: [],
    REFUNDED: [],
    // unused for BUY
    AWAITING_CRYPTO: [],
    CRYPTO_DETECTED: [],
    CONFIRMING: [],
    CRYPTO_CONFIRMED: [],
    GNF_RESERVED: [],
    PAYOUT_PENDING: [],
    PAYOUT_PROCESSING: [],
  } as Record<S, S[]>,
  TERMINAL,
);

export const SELL_TRANSITIONS = new TransitionTable<S>(
  'CryptoOrder(SELL)',
  {
    CREATED: ['QUOTE_LOCKED', 'CANCELLED', 'EXPIRED'],
    QUOTE_LOCKED: ['AWAITING_CRYPTO', 'CANCELLED', 'EXPIRED'],
    AWAITING_CRYPTO: ['CRYPTO_DETECTED', 'EXPIRED', 'CANCELLED', 'UNDER_REVIEW'],
    CRYPTO_DETECTED: ['CONFIRMING', 'UNDER_REVIEW', 'FAILED'],
    CONFIRMING: ['CRYPTO_CONFIRMED', 'UNDER_REVIEW', 'FAILED'],
    CRYPTO_CONFIRMED: ['GNF_RESERVED', 'UNDER_REVIEW'],
    GNF_RESERVED: ['PAYOUT_PENDING', 'UNDER_REVIEW'],
    PAYOUT_PENDING: ['PAYOUT_PROCESSING', 'UNDER_REVIEW', 'FAILED'],
    PAYOUT_PROCESSING: ['COMPLETED', 'UNDER_REVIEW', 'FAILED'],
    UNDER_REVIEW: ['GNF_RESERVED', 'PAYOUT_PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED'],
    COMPLETED: [],
    FAILED: [],
    EXPIRED: [],
    CANCELLED: [],
    REFUNDED: [],
    // unused for SELL
    USDT_RESERVED: [],
    AWAITING_PAYMENT: [],
    PAYMENT_DETECTED: [],
    PAYMENT_RECONCILING: [],
    PAYMENT_VERIFIED: [],
    USDT_PROCESSING: [],
    USDT_SENT: [],
  } as Record<S, S[]>,
  TERMINAL,
);

export function tableFor(side: 'BUY_USDT' | 'SELL_USDT') {
  return side === 'BUY_USDT' ? BUY_TRANSITIONS : SELL_TRANSITIONS;
}
